version: 2
jobs:
  build:
    docker:
      - image: golang:1.13
    environment:
      GO111MODULE: "on"
    working_directory: /ledger-go
    steps:
      - checkout
      - run: go build -mod=readonly ledger.go apduWrapper.go
      - run: go test
workflows:
  version: 2
  build_all:
    jobs:
      - build
